import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie DB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} className="bg-black">                           {/*unable to find a workarround but it is working for bg color */}
        <Header></Header>                                                               {/*fixing a header component commong for all */}
        <main>{children}</main>                                                         
      </body>
    </html>
  );
}
